### ISSUE TITLE
Bug in list_entries()

### ISSUE THREAD

**Issue by bryan831** [googleapis/python-datacatalog#85]
Hi there,
I am using the Python Data Catalog API.
There seems to be a bug in the `list_entries()` function.

I have my `parent` argument as `'projects/[my-project-id]/locations/asia-southeast1/entryGroups/@bigquery'`.
I get the error message 
```
google.api_core.exceptions.InvalidArgument: 400 a non-special dataset contains '@'; The two parts of the invalid dataset id are as follows: 'project=[my-project-id], dataset=@bigquery@asia-southeast1. If you used the dotted string format for the dataset id and believe your dataset is actually valid, you may try the full resource name (projects/.../datasets/...).
```
It seems like the function cannot handle the special `@bigquery` `EntryGroup`?

**Comment by tswast** [comment]
Thank you for the report @bryan831 !

This sounds like an issue with the backend API rather than the Python client. I suggest filing a support ticket to get this routed to the right team https://cloud.google.com/support Alternatively, you may file an issue on the public tracker here: https://issuetracker.google.com/issues/new?component=655468&template=1284353

**Comment by apalmercari** [comment]
@tswast Any update on this?

**Comment by tswast** [comment]
@apalmercari I closed this issue as it's a backend issue. We didn't hear back from the original reporter if they filed a public issue or support ticket. Feel free to do as I suggested if this is also affecting you.

**Comment by apalmercari** [comment]
@tswast   I have filed a issue https://issuetracker.google.com/issues/192655612
